version: '3.3'

services:
  tg-connection-base:
    image: tg-connection-base
    build: ./
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    env_file:
      - .env