version: '3.3'

services:
  tg-connection-base:
    image: tg-connection-base
    build: ./
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: 'redis:latest'
    env_file:
      - .env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - db-data: ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
volumes:
  db-data:
